# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target "FoundationSafety" do
  pod "FoundationSafety", :path => "../"
end

# Uncomment the following lines to add testing dependencies
target "FoundationSafetyTests" do
  pod 'Kiwi/XCTest'
end

